In [1]:
import pandas as pd
import requests

In [4]:
response = requests.get('https://api.rawg.io/api/platforms?key=0df81f5365794dbfb53dcbce328dc4cc')

In [9]:
df = pd.DataFrame(response.json()['results'])[['id','name','slug','games_count','year_start','year_end']]

In [10]:
df

,id,name,slug,games_count,year_start,year_end
0,4,PC,pc,562066,NaN,None
1,187,PlayStation 5,playstation5,1536,2020.0,None
2,1,Xbox One,xbox-one,5745,NaN,None
3,18,PlayStation 4,playstation4,7045,NaN,None
4,186,Xbox Series S/X,xbox-series-x,1287,2020.0,None
5,7,Nintendo Switch,nintendo-switch,5789,NaN,None
6,3,iOS,ios,77454,NaN,None
7,21,Android,android,52536,NaN,None
8,8,Nintendo 3DS,nintendo-3ds,1682,NaN,None
9,9,Nintendo DS,nintendo-ds,2506,NaN,None
10,13,Nintendo DSi,nintendo-dsi,37,NaN,None
11,5,macOS,macos,108208,NaN,None
12,6,Linux,linux,80556,NaN,None
13,14,Xbox 360,xbox360,2833,NaN,None
14,80,Xbox,xbox-old,881,NaN,None
15,16,PlayStation 3,playstation3,3209,NaN,None
16,15,PlayStation 2,playstation2,3151,NaN,None
17,27,PlayStation,playstation1,1699,NaN,None
18,19,PS Vita,ps-vita,1461,NaN,None
19,17,PSP,psp,1456,NaN,None
20,10,Wii U,wii-u,1114,NaN,None
21,11,Wii,wii,2238,NaN,None
22,105,GameCube,gamecube,673,NaN,None
23,83,Nintendo 64,nintendo-64,363,NaN,None
24,24,Game Boy Advance,game-boy-advance,964,NaN,None
25,43,Game Boy Color,game-boy-color,429,NaN,None
26,26,Game Boy,game-boy,617,NaN,None
27,79,SNES,snes,991,NaN,None
28,49,NES,nes,1025,NaN,None
29,55,Classic Macintosh,macintosh,675,NaN,None
30,41,Apple II,apple-ii,424,NaN,None
31,166,Commodore / Amiga,commodore-amiga,2084,NaN,None
32,28,Atari 7800,atari-7800,64,NaN,None
33,31,Atari 5200,atari-5200,64,NaN,None
34,23,Atari 2600,atari-2600,294,NaN,None
35,22,Atari Flashback,atari-flashback,30,NaN,None
36,25,Atari 8-bit,atari-8-bit,309,NaN,None
37,34,Atari ST,atari-st,836,NaN,None
38,46,Atari Lynx,atari-lynx,57,NaN,None
39,50,Atari XEGS,atari-xegs,22,NaN,None
40,167,Genesis,genesis,850,NaN,None
41,107,SEGA Saturn,sega-saturn,378,NaN,None
42,119,SEGA CD,sega-cd,163,NaN,None
43,117,SEGA 32X,sega-32x,46,NaN,None
44,74,SEGA Master System,sega-master-system,240,NaN,None
45,106,Dreamcast,dreamcast,380,NaN,None
46,111,3DO,3do,101,NaN,None
47,112,Jaguar,jaguar,40,NaN,None
48,77,Game Gear,game-gear,230,NaN,None
49,12,Neo Geo,neogeo,126,NaN,None

In [11]:
df =pd.DataFrame()

In [12]:
df

Empty DataFrame
Columns: []
Index: []

In [15]:
for i in range(1,52):
  response = requests.get('https://api.rawg.io/api/platforms?key=0df81f5365794dbfb53dcbce328dc4cc')
  temp_df = pd.DataFrame(response.json()['results'])[['id','name','slug','games_count','year_start','year_end']]
  df = pd.concat([df, temp_df], ignore_index=True)

In [17]:
df

       id             name           slug  games_count  year_start year_end
0       4               PC             pc       562066         NaN     None
1     187    PlayStation 5   playstation5         1536      2020.0     None
2       1         Xbox One       xbox-one         5745         NaN     None
3      18    PlayStation 4   playstation4         7045         NaN     None
4     186  Xbox Series S/X  xbox-series-x         1287      2020.0     None
...   ...              ...            ...          ...         ...      ...
2545  106        Dreamcast      dreamcast          380         NaN     None
2546  111              3DO            3do          101         NaN     None
2547  112           Jaguar         jaguar           40         NaN     None
2548   77        Game Gear      game-gear          230         NaN     None
2549   12          Neo Geo         neogeo          126         NaN     None

[2550 rows x 6 columns]

In [18]:
df.shape

(2550, 6)

In [20]:
df.to_csv('games.csv')